# Generated by Django 3.2.8 on 2021-12-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('diraize', models.ImageField(upload_to='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('duration', models.ImageField(upload_to='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('freqwrd', models.TextField()),
                ('tnscript', models.CharField(max_length=255)),
                ('nospeaker', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_audio', models.FileField(upload_to='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('sp_emo', models.ImageField(upload_to='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('sp_emobar', models.ImageField(upload_to='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.audio')),
            ],
        ),
    ]
