# Generated by Django 3.2.8 on 2021-12-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='diraize',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='freqwrd',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='nospeaker',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='tnscript',
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
