# Generated by Django 3.2.8 on 2021-12-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20211222_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='name',
        ),
    ]
