# Generated by Django 3.2.8 on 2022-01-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_audio_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FilePathField(path='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('diraize', models.FilePathField(path='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('duration', models.FilePathField(path='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('freqwrd', models.TextField()),
                ('tnscript', models.CharField(max_length=255)),
                ('nospeaker', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_audio', models.FilePathField(path='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('sp_emo', models.FilePathField(path='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('sp_emobar', models.FilePathField(path='C:\\Users\\ADMIN\\Documents\\V\\Voice-Call-Analyser\\project\\media')),
                ('audiofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.audios')),
            ],
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
