# Generated by Django 3.2.8 on 2022-01-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20220117_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audios',
            name='diraize',
        ),
        migrations.RemoveField(
            model_name='audios',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='audios',
            name='freqwrd',
        ),
        migrations.RemoveField(
            model_name='audios',
            name='nospeaker',
        ),
        migrations.RemoveField(
            model_name='audios',
            name='tnscript',
        ),
        migrations.AlterField(
            model_name='audios',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
