# Generated by Django 3.2.8 on 2022-01-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20220117_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='nospeaker',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
